##########################
#   LOG configurations   #
##########################
[log]
level = "debug" # set log level
[log.file]
# write log to file or not（Writing logs to file or console cannot be satisfied at the same time）.
enabled = false # enable logging to log files or not.
rotate = "hour" #[day,hour,minute] ，set rotate level
path = "./logs" # set log path

#live server configurations
##########################
#   RTMP configurations  #
##########################
[rtmp]
enabled = true #enable the RTMP media protocol or not
port = 1935 #specify the RTMP protocol listening port.
gop_num = 0 #specify the cache GOP count for instant playback.（may increase latency）
# pull streams from other server node.
[rtmp.pull]
enabled = false # enable static pulling or not, if the stream is not available locally, fetch it from the configured server.
address = "192.168.0.1" # the server address to pull from
port = 1935 # the server port to pull from
# push streams to other server node.
[[rtmp.push]]
enabled = false  # enable static repushing. After receiving RTMP streams on the local machine, repush them to other nodes. Supports configuring multiple remote nodes
address = "localhost" # the server address to repush to
port = 1936 # the server port to repush to
[[rtmp.push]]
enabled = false
address = "192.168.0.3"
port = 1935
[rtmp.auth] 
pull_enabled = true # enable pulling stream authentication or not.
push_enabled = true  # enable pushing stream authentication or not.
algorithm = "simple" # set authentication method, support simple authentication and MD5 authentication (fill in either "simple" or "md5" separately).
[authsecret]
# used for simple authentication 
key = "whatever"
password = "thisisthepassword"