# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_THREADS "0")
set(CPACK_BUILD_SOURCE_DIRS "/home/bean/Documents/GitHub/dooptech-overwatcher/HeroWatcher;/home/bean/Documents/GitHub/dooptech-overwatcher/HeroWatcher/build_x86_64")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENTS_ALL "")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_DEBUGINFO_PACKAGE "ON")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "bean.public@gmail.com")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS "ON")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "dooptech-herowatcher built using CMake")
set(CPACK_GENERATOR "DEB")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/bean/Documents/GitHub/dooptech-overwatcher/HeroWatcher/build_x86_64;dooptech-herowatcher;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH "/home/bean/Documents/GitHub/dooptech-overwatcher/HeroWatcher/cmake/common;/home/bean/Documents/GitHub/dooptech-overwatcher/HeroWatcher/cmake/linux")
set(CPACK_NSIS_DISPLAY_NAME "dooptech-herowatcher 1.0.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "\$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "dooptech-herowatcher 1.0.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/bean/Documents/GitHub/dooptech-overwatcher/HeroWatcher/build_x86_64/CPackConfig.cmake")
set(CPACK_OUTPUT_FILE_PREFIX "/home/bean/Documents/GitHub/dooptech-overwatcher/HeroWatcher/release")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "dooptech-herowatcher built using CMake")
set(CPACK_PACKAGE_FILE_NAME "dooptech-herowatcher-1.0.0-x86_64-linux-gnu")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "dooptech-herowatcher 1.0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "dooptech-herowatcher 1.0.0")
set(CPACK_PACKAGE_NAME "dooptech-herowatcher")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "1.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PRODUCTBUILD_DOMAINS "ON")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/usr/share/cmake-3.31/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.31/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.31/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "ON")
set(CPACK_SOURCE_GENERATOR "TXZ")
set(CPACK_SOURCE_IGNORE_FILES ".*~\$;\\.git/;\\.github/;\\.gitignore;\\.ccache/;build_.*;cmake/\\.CMakeBuildNumber;release/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/bean/Documents/GitHub/dooptech-overwatcher/HeroWatcher/build_x86_64/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "dooptech-herowatcher-1.0.0-source")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_VERBATIM_VARIABLES "YES")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/bean/Documents/GitHub/dooptech-overwatcher/HeroWatcher/build_x86_64/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
